runtime: java17
service: WikiChef
entrypoint: java -Dserver.port=$PORT -jar target/WikiChef-0.0.1-SNAPSHOT.jar

env_variables:
  # Instancia Cloud SQL: PROJECT:REGION:INSTANCE
  INSTANCE_CONNECTION_NAME: "algebraic-argon-481008-r5:europe-west2:desarrollo-cloud-instance"

  # URL JDBC con socket factory
  SPRING_DATASOURCE_URL: "jdbc:postgresql:///WikiChef?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${INSTANCE_CONNECTION_NAME}"

  # Credenciales BD
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root1234@"

  # JWT Key (idealmente desde Secret Manager)
  JWT_SIGNING_KEY: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"